on: push

jobs:
  test:
    name: Testing with Go {{ matrix.goversion }} version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goversion: [1.16, 1.15, 1.14]

    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make test